### ISSUE TITLE
Starbird shell - Local development not working on SSL

### ISSUE THREAD

**Issue by brewsoftware** [MYOB-Technology/starbird-issues#18]
Hey,
   So I've set "enableLogin": true to enable IDAM authentication. (local.json)

I have also flicked the "https":1 flag to enable/disable SSL on the local server.

When the redirect url's are changed to http://localhost:3000 the sit server denies the redirection. When it's set to https://localhost:3000 and the https:1 flag is set the local server does not come up under "npm run start".

The "npm run client" works if we set the HTTPS=true flag on the client but all the starbird shell dependencies are missing so that doesn't work either. 

using the HTTPS=true flag on the npm start server doesn't appear to change anything either.

----------------------

There are a few things that probably need to be looked at:
 * Why "HTTPS=true npm run server" isn't starting the app in HTTPS mode for local development
 * Can the SIT config be changed to redirect back to http://localhost:3000 for development
 * What does the "https":1 flag do in the core.json, I would assume that this turns on SSL, do we also need to provide a PEM file in a particular format?

**Comment by igormyob** [comment]
Hello @brewsoftware , I don't think the node server is supporting https at the moment, so the flag is just for some internal logic of redirects, when you host the server. I'm also not sure if the STS OAUTH configuration of redirect urls has the https version of localhost. Do you have a requirement for running https locally?

That being said, if you want to use Idam (enableLogin:1), you should not be using the node server (running `npm run start`) but using the `window.Shell.auth.getToken(resource)` instead. That endpoint exchanges the STS token you obtained in the node server for an IDAM token.
If you don't need the STS part of it, running `npm run client` with enableLogin set to true should do the trick. Could you be more specific on what is missing in that scenario?

**Comment by brewsoftware** [comment]
Hey, so we don't need to support SSL but when we call the sit authenticator for an IDAM authentication session I get an error (Try plugging the following into a browser). Then switch the callback URL to https and see what happens.

https://sit.login.myob.com/oauth2/authorize?response_type=id_token%20token&client_id=practice-online-web&redirect_uri=http://localhost:3000/callback&resource=starbird&scope=openid&state=9c9b8a58-02e9-42ea-903e-acf10e07e59f_e30=&nonce=55d09da0-7aa3-4c14-8297-4279cbf0ec55&client-request-id=b90b303c-d226-444b-b33e-c988a3a29c6f&x-client-sku=js&x-client-ver=1.0.0

I think it would make sense to drop the https redirect from the SIT config to allow for local development?

**Comment by brewsoftware** [comment]
`npm run client` does seem to work to an extent but we get errors such as "React is not defined". 
If we then disable the bundle split it does work except that we get another error

Cannot read property 'module' of undefined
`window.Starbird.module.register(App, config.metadata.moduleName);`

when inspecting the terminal the window.Shell and window.Starbird objects are undefined.

**Comment by igormyob** [comment]
Concerning the idam https redirects, we just got confirmation from idam that it only supports https in SIT environment, which is why we had to do it that way ;(

**Comment by educalleja** [comment]
Hi @brewsoftware 
Sorry for the late reply. I think we now support SSL on the sandbox. The only thing you need to do is to enableLogin=true and set https: 1 in the core.json 
Remember to change the URLS in local.json too.

Not sure if the other issues have been addressed. I close this issue and if something is still a problem please let us know
