### ISSUE TITLE
[Nova][Watch]Disable polling by default on non-Windows machines (nice to have)

### ISSUE THREAD

**Issue by esteban-terem** [MYOB-Technology/starbird-issues#23]
Hi. Although it is already suggested in the [FAQ](https://github.com/MYOB-Technology/starbird-issues/wiki/Nova-FAQ) to remove `{poll: 1000}` on Unix-like machines, I'd be nice to have this configuration done automatically by the `watch.js` script (a new developer may not quickly realise that the high CPU usage is caused by that). Something like:

```js
//...
const isWin = process.platform === 'win32';
//...
  if (isWin) {
    watchOptions.poll = 1000;
  }
//...
```

Thank you.

**Comment by igormyob** [comment]
Thanks @esteban-terem for the idea/code! I've added this to the template, should be live on the next release.
