### ISSUE TITLE
Introduce specifier for module wrapper element.

### ISSUE THREAD

**Issue by AndrewKevin** [MYOB-Technology/starbird-issues#24]
Hi Team,

The Assets module has a sticky header/footers that need to be rendered below the Shell top-bar and bottom edge of the window. It would be good to have a direct method locating the module wrapper element by id or class. Element in question is - https://github.com/MYOB-Technology/ps-shell/blob/9136cec2d6c67eddb5222c9397844e8a079f345c/src/client-centric/MainLayout.jsx#L40

Currently, we can use `x-shell-main` then programmatically traverse the DOM tree to find this node, but this is ugly and we would like to avoid this.

Additionally a quick Github search show `x-shell-main` isn't being used by any other teams, so it would be OK to remove it later.

**Comment by danscott-myob** [comment]
Perhaps passing a ref or selector to your module on mount (via props) would work? That'd minimize the coupling/magic string usage.

**Comment by AndrewKevin** [comment]
@danscott-myob a ref would be great!

**Comment by AndrewKevin** [comment]
@esteban-terem @vishaljain83 FYI

**Comment by AndrewKevin** [comment]
hey @danscott-myob any further thoughts on this?

**Comment by danscott-myob** [comment]
@AndrewKevin Sorry, this dropped off the radar in the face of all our Feelix update fun. I'll discuss this with the team today and get back to you on it.

**Comment by danscott-myob** [comment]
@AndrewKevin The above commit should solve your issue 👍
