### ISSUE TITLE
React 16.0 Compatability

### ISSUE THREAD

**Issue by brewsoftware** [MYOB-Technology/starbird-issues#4]
Hi Guys,
   I have noticed that when importing the DateTimePicker component it is throwing errors relating to cannot read property of undefined. 

This relates to a split in the latest React framework. In React > 15.5 the "PropTypes" library has been broken out of the core framework. In the latest react version 16.0 this means that PropTypes needs to be explicitly imported.

15.5
import React from 'react'

React.PropTypes.func.isRequired

16.0
import React from 'react'
import PropTypes from 'prop-types'

PropTypes.func.isRequired

If this could be updated in the base DateTimePicker componentry it would be great.

Cheers,
Jason

**Comment by richard-lopes** [comment]
To share with the Feelix team.

**Comment by igormyob** [comment]
Feelix has been updated to react16. Shell update is incoming this month. Closing.
